### PR TITLE
Replace anaconda-notebook with anaconda-nb-extensions.

### PR DESCRIPTION
**Pull request by damianavila**
Just that...

### CODE REVIEW

**Comment by damianavila** [comment]
This is now tied to #140

**Comment by damianavila** [comment]
win builds are not working now

**Comment by malev** [comment]
I've build this package in win-64 and that went fine. Then I ran:
`conda install anaconda-nb-extensions --use-local -c anaconda-nb-extensions`
and this is what I a getting:

```
anaconda-nb-ex 100% |###############################| Time: 0:00:00   0.00  B/s
Extracting packages ...
[      COMPLETE      ]|##################################################| 100%
Unlinking packages ...
menuinst Exception:Traceback (most recent call last):                    |  35%
  File "C:\Miniconda2\lib\site-packages\conda\install.py", line 343, in mk_menus
TypeError: install() got an unexpected keyword argument 'root_prefix'
[      COMPLETE      ]|##################################################| 100%
Linking packages ...
menuinst Exception:Traceback (most recent call last):                    |  53%
  File "C:\Miniconda2\lib\site-packages\conda\install.py", line 343, in mk_menus
    try:
TypeError: install() got an unexpected keyword argument 'root_prefix'
[      COMPLETE      ]|##################################################| 100%

malev@MALEV-PC C:\Users\malev\Documents\anaconda-nb-extensions
``

**Comment by malev** [comment]
Building and installing in osx seems to be working ok.

**Comment by damianavila** [comment]
Thanks for the feedback, testing in my local setup to see if I can reproduce the issue

**Comment by damianavila** [comment]
@malev, I can not reproduce the issue in my win VM...
I guess I will merge this one as is and the deal with the issue if someone else can reproduce it.

**Pull request merged**
